#!/bin/bash
if [ -f "/usr/bin/chonosSysConf" ] ; then
    chonosSysConf stop
    rm /opt/chonos-embMAS/lib/tomcat/webapps/*.war
fi

if [ -d "/opt/chonos-embMAS/lib/tomcat/webapps/sysconfig" ] ; then
    rm -rf /opt/chonos-embMAS/lib/tomcat/webapps/sysconfig
fi

if [ -d "/opt/chonos-embMAS/lib/tomcat/webapps/chonIDE-project" ] ; then
	rm -rf /opt/chonos-embMAS/lib/tomcat/webapps/chonIDE-project
fi

if [ -d "/opt/chonos-embMAS/lib/tomcat/webapps/chonide" ] ; then
	rm -rf /opt/chonos-embMAS/lib/tomcat/webapps/chonide
fi

if [ -d "/opt/chonos-embMAS/lib/tomcat/logs" ] ; then
	rm -rf /opt/chonos-embMAS/lib/tomcat/logs/*
fi

if [ -d "/opt/chonos-embMAS/lib/tomcat" ] ; then
	rm -rf /opt/chonos-embMAS/lib/tomcat
fi